# Generated by Django 4.2.13 on 2024-10-07 15:48

import business_forms.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Отметка времени')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город проживания')),
                ('currency', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('rub', 'Рубли'), ('usd', 'Доллары США'), ('eur', 'Евро'), ('cny', 'Юани'), ('aed', 'Дирхамы'), ('other', 'Другая валюта')], max_length=255, null=True, verbose_name='Укажите валюту инвестирования (можно отметить несколько вариантов):')),
                ('age', models.CharField(blank=True, choices=[('under_23', 'До 23 лет'), ('24_40', 'От 24 до 40 лет'), ('41_60', 'От 41 до 60 лет'), ('over_60', 'Старше 60 лет')], max_length=255, null=True, verbose_name='Укажите информацию о Вашем возрасте:')),
                ('investment_goal', models.CharField(blank=True, choices=[('inflation_protection', 'Защита средств от инфляции'), ('pension', 'Прибавка к пенсии'), ('additional_income', 'Получение дополнительного дохода'), ('children_future', 'На будущее детей'), ('other', 'Другая причина')], max_length=255, null=True, verbose_name='Укажите Вашу цель инвестирования (пожалуйста, отметьте один вариант)')),
                ('investment_period', models.CharField(blank=True, choices=[('less_than_3', 'Менее 3 лет'), ('3_to_5', 'От 3 до 5 лет'), ('5_to_10', 'От 5 до 10 лет'), ('more_than_10', 'Свыше 10 лет')], max_length=255, null=True, verbose_name='Укажите срок инвестирования ')),
                ('available_sum', models.CharField(blank=True, choices=[('10_30', 'От 10 до 30 млн. рублей'), ('30_100', 'От 30 до 100 млн. рублей'), ('over_100', 'Свыше 100 млн. рублей')], max_length=255, null=True, verbose_name='Укажите информацию о наличии и сумме Ваших сбережений')),
                ('status', models.IntegerField(choices=[(1, 'Открыт'), (2, 'Связался, жду ответ'), (3, 'Не отвечает')], default=1, verbose_name='Статус')),
                ('additional_question', models.TextField(blank=True, null=True, verbose_name='Для дополнительных вопросов:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера')),
            ],
            options={
                'verbose_name': 'запись в анкете',
                'verbose_name_plural': 'Анкета записи',
            },
            bases=(models.Model, business_forms.models.BaseModelForm),
        ),
        migrations.CreateModel(
            name='BusinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_photo_path)),
                ('spasibo_photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_spasibo_path)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Конфигурации форм',
                'verbose_name_plural': 'Конфигурации форм',
            },
        ),
    ]
